version: "2"

services:
  nginx:
    volumes:
      - ./resource/:/app
      - ./my_server_block.conf:/opt/bitnami/nginx/conf/server_blocks/my_server_block.conf:ro
    image: "docker.io/bitnami/nginx:1.19-debian-10"
    ports:
      - "82:8080"
